import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { TopButton } from "./components/TopButton";
import { SideButton } from "./components/SideButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex min-h-screen items-center justify-center  relative font-sans bg-neutral-950 ">
          <div className="h-full w-full absolute bg-[radial-gradient(circle_at_center,rgba(0,0,0,0)_40%,rgba(0,0,0,0.3)_100%)]  ">
            {/* <div className="h-full w-full bg-[url('/bg.jpg')] blur-xl opacity-5 saturate-30 "></div> */}
            <div className="w-full h-full bg-[repeating-linear-gradient(90deg,gray_0_2px,_transparent_1px_30px)] opacity-5  ">
              <div className="w-full h-full bg-[repeating-linear-gradient(0deg,gray_0_2px,_transparent_1px_30px)] "></div>
            </div>
          </div>
          <div className="w-[50%] flex flex-col gap-2 items-start shadow-white/5 shadow-inner relative bg-neutral-950 backdrop-blur-3xl justify-start min-h-screen my-30 p-10  border    border-dashed  border-neutral-800">
            <TopButton />
            <SideButton />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
